// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.alkaid.pearlharbor.net;

public final class PacketProto {
  private PacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CS_HelloWorldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet.CS_HelloWorld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 _int = 1;</code>
     */
    boolean hasInt();
    /**
     * <code>required int32 _int = 1;</code>
     */
    int getInt();

    /**
     * <code>required float _float = 2;</code>
     */
    boolean hasFloat();
    /**
     * <code>required float _float = 2;</code>
     */
    float getFloat();

    /**
     * <code>required int64 _long = 3;</code>
     */
    boolean hasLong();
    /**
     * <code>required int64 _long = 3;</code>
     */
    long getLong();

    /**
     * <code>required string _string = 4;</code>
     */
    boolean hasString();
    /**
     * <code>required string _string = 4;</code>
     */
    java.lang.String getString();
    /**
     * <code>required string _string = 4;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();
  }
  /**
   * Protobuf type {@code Packet.CS_HelloWorld}
   */
  public static final class CS_HelloWorld extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Packet.CS_HelloWorld)
      CS_HelloWorldOrBuilder {
    // Use CS_HelloWorld.newBuilder() to construct.
    private CS_HelloWorld(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CS_HelloWorld(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CS_HelloWorld defaultInstance;
    public static CS_HelloWorld getDefaultInstance() {
      return defaultInstance;
    }

    public CS_HelloWorld getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CS_HelloWorld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              Int_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              Float_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              Long_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              String_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_CS_HelloWorld_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_CS_HelloWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.class, com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.Builder.class);
    }

    public static com.google.protobuf.Parser<CS_HelloWorld> PARSER =
        new com.google.protobuf.AbstractParser<CS_HelloWorld>() {
      public CS_HelloWorld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS_HelloWorld(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CS_HelloWorld> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int _INT_FIELD_NUMBER = 1;
    private int Int_;
    /**
     * <code>required int32 _int = 1;</code>
     */
    public boolean hasInt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 _int = 1;</code>
     */
    public int getInt() {
      return Int_;
    }

    public static final int _FLOAT_FIELD_NUMBER = 2;
    private float Float_;
    /**
     * <code>required float _float = 2;</code>
     */
    public boolean hasFloat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float _float = 2;</code>
     */
    public float getFloat() {
      return Float_;
    }

    public static final int _LONG_FIELD_NUMBER = 3;
    private long Long_;
    /**
     * <code>required int64 _long = 3;</code>
     */
    public boolean hasLong() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 _long = 3;</code>
     */
    public long getLong() {
      return Long_;
    }

    public static final int _STRING_FIELD_NUMBER = 4;
    private java.lang.Object String_;
    /**
     * <code>required string _string = 4;</code>
     */
    public boolean hasString() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string _string = 4;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = String_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          String_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string _string = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = String_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        String_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      Int_ = 0;
      Float_ = 0F;
      Long_ = 0L;
      String_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFloat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLong()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasString()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, Int_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, Float_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, Long_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStringBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, Int_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, Float_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, Long_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStringBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet.CS_HelloWorld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet.CS_HelloWorld)
        com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_CS_HelloWorld_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_CS_HelloWorld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.class, com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.Builder.class);
      }

      // Construct using com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        Int_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        Float_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        Long_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        String_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_CS_HelloWorld_descriptor;
      }

      public com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld getDefaultInstanceForType() {
        return com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.getDefaultInstance();
      }

      public com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld build() {
        com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld buildPartial() {
        com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld result = new com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.Int_ = Int_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.Float_ = Float_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.Long_ = Long_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.String_ = String_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld) {
          return mergeFrom((com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld other) {
        if (other == com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld.getDefaultInstance()) return this;
        if (other.hasInt()) {
          setInt(other.getInt());
        }
        if (other.hasFloat()) {
          setFloat(other.getFloat());
        }
        if (other.hasLong()) {
          setLong(other.getLong());
        }
        if (other.hasString()) {
          bitField0_ |= 0x00000008;
          String_ = other.String_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInt()) {
          
          return false;
        }
        if (!hasFloat()) {
          
          return false;
        }
        if (!hasLong()) {
          
          return false;
        }
        if (!hasString()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alkaid.pearlharbor.net.PacketProto.CS_HelloWorld) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int Int_ ;
      /**
       * <code>required int32 _int = 1;</code>
       */
      public boolean hasInt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 _int = 1;</code>
       */
      public int getInt() {
        return Int_;
      }
      /**
       * <code>required int32 _int = 1;</code>
       */
      public Builder setInt(int value) {
        bitField0_ |= 0x00000001;
        Int_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 _int = 1;</code>
       */
      public Builder clearInt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        Int_ = 0;
        onChanged();
        return this;
      }

      private float Float_ ;
      /**
       * <code>required float _float = 2;</code>
       */
      public boolean hasFloat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float _float = 2;</code>
       */
      public float getFloat() {
        return Float_;
      }
      /**
       * <code>required float _float = 2;</code>
       */
      public Builder setFloat(float value) {
        bitField0_ |= 0x00000002;
        Float_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float _float = 2;</code>
       */
      public Builder clearFloat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        Float_ = 0F;
        onChanged();
        return this;
      }

      private long Long_ ;
      /**
       * <code>required int64 _long = 3;</code>
       */
      public boolean hasLong() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 _long = 3;</code>
       */
      public long getLong() {
        return Long_;
      }
      /**
       * <code>required int64 _long = 3;</code>
       */
      public Builder setLong(long value) {
        bitField0_ |= 0x00000004;
        Long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 _long = 3;</code>
       */
      public Builder clearLong() {
        bitField0_ = (bitField0_ & ~0x00000004);
        Long_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object String_ = "";
      /**
       * <code>required string _string = 4;</code>
       */
      public boolean hasString() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string _string = 4;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = String_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            String_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string _string = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = String_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          String_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string _string = 4;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        String_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string _string = 4;</code>
       */
      public Builder clearString() {
        bitField0_ = (bitField0_ & ~0x00000008);
        String_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>required string _string = 4;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        String_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Packet.CS_HelloWorld)
    }

    static {
      defaultInstance = new CS_HelloWorld(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Packet.CS_HelloWorld)
  }

  public interface SC_HelloWorldResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet.SC_HelloWorldResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 _resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required int32 _resultCode = 1;</code>
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code Packet.SC_HelloWorldResult}
   */
  public static final class SC_HelloWorldResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Packet.SC_HelloWorldResult)
      SC_HelloWorldResultOrBuilder {
    // Use SC_HelloWorldResult.newBuilder() to construct.
    private SC_HelloWorldResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SC_HelloWorldResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SC_HelloWorldResult defaultInstance;
    public static SC_HelloWorldResult getDefaultInstance() {
      return defaultInstance;
    }

    public SC_HelloWorldResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SC_HelloWorldResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ResultCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_SC_HelloWorldResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_SC_HelloWorldResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.class, com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.Builder.class);
    }

    public static com.google.protobuf.Parser<SC_HelloWorldResult> PARSER =
        new com.google.protobuf.AbstractParser<SC_HelloWorldResult>() {
      public SC_HelloWorldResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_HelloWorldResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SC_HelloWorldResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int _RESULTCODE_FIELD_NUMBER = 1;
    private int ResultCode_;
    /**
     * <code>required int32 _resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 _resultCode = 1;</code>
     */
    public int getResultCode() {
      return ResultCode_;
    }

    private void initFields() {
      ResultCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ResultCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ResultCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet.SC_HelloWorldResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet.SC_HelloWorldResult)
        com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_SC_HelloWorldResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_SC_HelloWorldResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.class, com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.Builder.class);
      }

      // Construct using com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ResultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alkaid.pearlharbor.net.PacketProto.internal_static_Packet_SC_HelloWorldResult_descriptor;
      }

      public com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult getDefaultInstanceForType() {
        return com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.getDefaultInstance();
      }

      public com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult build() {
        com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult buildPartial() {
        com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult result = new com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ResultCode_ = ResultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult) {
          return mergeFrom((com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult other) {
        if (other == com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alkaid.pearlharbor.net.PacketProto.SC_HelloWorldResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ResultCode_ ;
      /**
       * <code>required int32 _resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 _resultCode = 1;</code>
       */
      public int getResultCode() {
        return ResultCode_;
      }
      /**
       * <code>required int32 _resultCode = 1;</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        ResultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 _resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ResultCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Packet.SC_HelloWorldResult)
    }

    static {
      defaultInstance = new SC_HelloWorldResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Packet.SC_HelloWorldResult)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_CS_HelloWorld_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Packet_CS_HelloWorld_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_SC_HelloWorldResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Packet_SC_HelloWorldResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Packet.proto\022\006Packet\"M\n\rCS_HelloWorld\022" +
      "\014\n\004_int\030\001 \002(\005\022\016\n\006_float\030\002 \002(\002\022\r\n\005_long\030\003" +
      " \002(\003\022\017\n\007_string\030\004 \002(\t\"*\n\023SC_HelloWorldRe" +
      "sult\022\023\n\013_resultCode\030\001 \002(\005B)\n\032com.alkaid." +
      "pearlharbor.netB\013PacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Packet_CS_HelloWorld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_CS_HelloWorld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Packet_CS_HelloWorld_descriptor,
        new java.lang.String[] { "Int", "Float", "Long", "String", });
    internal_static_Packet_SC_HelloWorldResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Packet_SC_HelloWorldResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Packet_SC_HelloWorldResult_descriptor,
        new java.lang.String[] { "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
